/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  identity: {
    Account: () => import('#app/identity/controllers/account_controller'),
    Login: () => import('#app/identity/controllers/login_controller'),
    Logout: () => import('#app/identity/controllers/logout_controller'),
    RegisterUser: () => import('#app/identity/controllers/register_user_controller'),
  },
  mobility: {
    Favorites: () => import('#app/mobility/controllers/favorites_controller'),
    JourneyPlanner: () => import('#app/mobility/controllers/journey_planner_controller'),
    Lines: () => import('#app/mobility/controllers/lines_controller'),
    Sources: () => import('#app/mobility/controllers/sources_controller'),
    Traffic: () => import('#app/mobility/controllers/traffic_controller'),
  },
}
